#!/usr/bin/env python3

"""
Author: Mingyang Wang
Student No.: 1067192
Description: Implementation of a hidden Markov model, the hidden part is match
state (match, deletion, insertion), and the observed part is an AA sequence,
which is generated by randomly picking on its probability the residue from
all possible residues at each match state based.
Usage: python <script.py> <input_fasta_filename.fasta>
    where <script.py>, str, the name this script
    <input_fasta_filename.fasta>, str, the name of input fasta file, containing
    multiple AA sequences with same length.
    for example: test.fasta, develop.fasta
"""

from sys import argv
import random

# Background amino acid probabilities
pa = { 'A':0.074, 'C':0.025, 'D':0.054, 'E':0.054, 'F':0.047, 'G':0.074,
    'H':0.026, 'I':0.068, 'L':0.099, 'K':0.058, 'M':0.025, 'N':0.045,
    'P':0.039, 'Q':0.034, 'R':0.052, 'S':0.057, 'T':0.051, 'V':0.073,
    'W':0.013, 'Y':0.034 }

def fasta_reader(filename):
    """Parse a FASTQ file into a list of strings

    filename: str, name of the fasta file
    returns: seq_ls, a list of strings, where each of the string is the sequence
    """
    seq_ls = [] #not for test_large.fasta
    with open(filename) as f:
        seq = ''
        for line in f:
            line = line.strip()
            if line == '':
                continue
            if line.startswith('>'):
                if seq != '':
                    seq_ls.append(seq)
                seq = ''
                continue

            seq += line

        if seq != '': #the last one
            seq_ls.append(seq)

    return seq_ls

def match_state_checker(seq_ls):
    """Create a list of the matching state for each residue position of sequence

    seq_ls: a list of strings, where each of the string is the AA sequence
    returns: match_state, a list of booleans, True means the position is a match
            state; False means the position is an insertion/non-match position.
    """
    #first checking if all sequence have the same length
    length = len(seq_ls[0])
    for seq in seq_ls:
        if length != len(seq):
            print(f'sequence length should be same')
            exit()
    #check which column is match
    sequence_length = len(seq_ls[0])
    col_num = len(seq_ls)
    match_state = [False] * sequence_length
    for i in range(sequence_length):
        count = 0
        for seq in seq_ls:
            if seq[i] != '-':
                count += 1

        if count >= col_num / 2:
            match_state[i] = True

    return match_state

def reduced_alignment_maker(seq_ls, match_state):
    """Remove non-match-state positions from each sequence.

    Parameters:
        seq_ls: A list of aligned amino acid sequences as strings.
        match_state: A list of booleans. True means the position is a match
         state and should be kept; False means the position should be removed.

    Returns: redu_seq_ls,
        A list of reduced sequences, where all non-match-state positions have
        been deleted.
    """
    unmatch_pos = []
    for i, state in enumerate(match_state):
        if state == False:
            unmatch_pos.append(i)

    redu_seq_ls = []
    for seq in seq_ls:
        seq_inls = list(seq)
        for index in sorted(unmatch_pos, reverse = True): #e.g.[6,4,1]
            #remove from the last, so the index of front part remained
            del seq_inls[index]

        redu_seq = ''.join(seq_inls)
        redu_seq_ls.append(redu_seq)

    return redu_seq_ls

def transitions_count(seq_ls, match_state):
    """Count transitions and emissions for a profile HMM.

    This function goes through each aligned sequence and converts every
    residue position into a profile HMM state. Match positions become match (M)
    or deletion states (D), while non-match positions become insertion states
    (I) if the character is not a gap. If it is under non-match state and a gap,
    it will be ignored.

    Parameters:
        seq_ls: A list of aligned amino acid sequences as strings.
        match_state: A list of booleans. True means the position is a match
            state; False means the position is an insertion/non-match position.

    Returns:
        transition_counts: A list of transition counts in the form of
                [[(previous_state, current_state), count], ...].
                where previous_state and current state are strings, and count
                is int.
        emission_counts: A list of emission counts in the form of
                [[(state, amino_acid), count], ...].
                where state and amino_acid are strings, and count
                is int.
    """
    transition_counts = []
    emission_counts = []

    for seq in seq_ls:
        previous_state = "Begin"
        match_count = 0

        for i, is_match in enumerate(match_state):
            letter = seq[i]

            if is_match:
                match_count += 1

                if letter == "-": #match and '-', it is deletion
                    current_state = f"D{match_count}"
                else: #match and not '-', it is matching
                    current_state = f"M{match_count}"

                    # count emission
                    emission = (current_state, letter)
                    found = False
                    for item in emission_counts:
                        if item[0] == emission: #already append before
                            item[1] += 1
                            found = True
                            break #break the for loop
                    if not found: # if found is still false, then......
                        emission_counts.append([emission, 1]) #first time append

            else:
                if letter == "-": # unmatch and '-', ignore completely
                    continue
                else: #unmatch and not '-', insertion
                    current_state = f"I{match_count}"

                    # count emission
                    emission = (current_state, letter)
                    found = False
                    for item in emission_counts:
                        if item[0] == emission:
                            item[1] += 1
                            found = True
                            break
                    if not found:
                        emission_counts.append([emission, 1])

            # count transition
            transition = (previous_state, current_state)
            found = False
            for item in transition_counts:
                if item[0] == transition:
                    item[1] += 1
                    found = True
                    break
            if not found:
                transition_counts.append([transition, 1])

            previous_state = current_state

        # final transition to End
        transition = (previous_state, "End")
        found = False
        for item in transition_counts:
            if item[0] == transition:
                item[1] += 1
                found = True
                break
        if not found:
            transition_counts.append([transition, 1])

    return transition_counts, emission_counts

def trans_count_normalize(transition_counts, emission_counts):
    """Normalize transition and emission counts into probabilities.

        Parameters:
            transition_counts: A list of transition counts in the form of
                [[(previous_state, current_state), count], ...].
                where previous_state and current state are strings, and count
                is int.
            emission_counts: A list of emission counts in the form of
                [[(state, amino_acid), count], ...].
                where state and amino_acid are strings, and count
                is int.

        Returns:
            trans_norm_dict: A dictionary where each key is a transition
                tuple, such as (previous_state, current_state),
                previous_state, current_state are strings, and each value
                is the normalized transition probability as float.
            emission_norm_dict: A dictionary where each key is an emission
                tuple, such as (state, amino_acid),
                previous_state, current_state are strings and each value is the
                normalized emission probability as float.
    """
    #for transition
    trans_total_dict = {}
    for trans_counts in transition_counts:
        trans_name = trans_counts[0][0]
        count = trans_counts[1]

        if trans_name not in trans_total_dict:
            trans_total_dict[trans_name] = count
        else:
            trans_total_dict[trans_name] += count

    trans_norm_dict = {}
    for trans_state in trans_total_dict:
        for trans_counts in transition_counts:
            if trans_state == trans_counts[0][0]:
                branch = trans_counts[0]
                count = trans_counts[1]
                total_count = trans_total_dict[trans_state]
                ratio = (count / total_count)
                trans_norm_dict[branch] = ratio

    #for emission
    emission_total_count = {}
    for counts in emission_counts:
        emission_name = counts[0][0]
        count = counts[1]

        if emission_name not in emission_total_count:
            emission_total_count[emission_name] = count
        else:
            emission_total_count[emission_name] += count

    emission_norm_dict = {}
    for state in emission_total_count:
        for counts in emission_counts:
            if state == counts[0][0]:
                branch = counts[0]
                count = counts[1]
                total_count = emission_total_count[state]
                ratio = (count / total_count)
                emission_norm_dict[branch] = ratio

    return trans_norm_dict, emission_norm_dict

def sample(events):
    """Return a key from dict based on the probabilities

    :events: dict of {string: probability}, probabilities can also be weights.
    :return: string
    """

    pick = random.choices(list(events.keys()),list(events.values()))[0]
    #the keys, which is the residue letter,
    #is randomly picked based on its probability as weight
    return pick

def hmm_sequence_generator(trans_norm_dict, emission_norm_dict):
    """Generate a sequence from a profile HMM.

      This function uses normalized transition and emission probabilities to
      randomly generate one hidden-state path and one residue sequence. Starting
      from the Begin state, it samples the next state until the End state is
      reached. The odds from previous state to next state is based on
      trans_norm_dict. Each Match states emit residues based on
      `emission_norm_dict`, while
      insertion states emit residues based on the background probability `pa`.
      Deletion emits nothing.

      Parameters:
           trans_norm_dict: A dictionary where each key is a transition
                tuple, such as (previous_state, current_state),
                previous_state, current_state are strings, and each value
                is the normalized transition probability as float.
           emission_norm_dict: A dictionary where each key is an emission
                tuple, such as (state, amino_acid),
                previous_state, current_state are strings and each value is the
                normalized emission probability as float.

      Returns:
            hidden_sequence: A list of generated hidden states as strings
            hmm_residue_sequence: A generated amino acid sequence as a string.
      """
    #convert to a dict for calling easier
    pre_to_next_dict = {}
    # {previous state: {next_state1: proba, next_state2: proba}}
    for transition, probability in trans_norm_dict.items():
        previous_state = transition[0]
        next_state = transition[1]

        if previous_state not in pre_to_next_dict:
            pre_to_next_dict[previous_state] = {}
            pre_to_next_dict[previous_state][next_state] = probability

        else:
            pre_to_next_dict[previous_state][next_state] = probability

    state_to_residue_dict = {}
    for emission, probability in emission_norm_dict.items():
        emission_state = emission[0]
        residue = emission[1]

        if emission_state not in state_to_residue_dict:
            state_to_residue_dict[emission_state] = {}
            state_to_residue_dict[emission_state][residue] = probability
        else:
            state_to_residue_dict[emission_state][residue] = probability

    #start calling the state

    current_state = 'Begin'
    hidden_sequence = []
    hmm_residue_sequence_ls = []
    while current_state != 'End':
        next_state = sample(pre_to_next_dict[current_state])
        if next_state != 'End':
            hidden_sequence.append(next_state)
            if next_state.startswith('M'):
                hmm_residue = sample(state_to_residue_dict[next_state])
                hmm_residue_sequence_ls.append(hmm_residue)

            elif next_state.startswith('I'):
                hmm_residue = sample(pa)
                hmm_residue_sequence_ls.append(hmm_residue)

        current_state = next_state
    hmm_residue_sequence = ''.join(hmm_residue_sequence_ls)
    return hidden_sequence, hmm_residue_sequence

def main():
    """Main function of this script"""
    if len(argv) != 2: #change the number
        print("Usage: python <script.py> <input_fasta_filename.fasta>")
        exit()


    ####Basic implement
    #filename
    infile = argv[1]
    #parsing and info collection
    seq_ls = fasta_reader(infile)
    match_state = match_state_checker(seq_ls)
    #reduced sequence
    redu_seq_ls = reduced_alignment_maker(seq_ls, match_state)
    #core part, transition and emission counts
    transition_counts, emission_counts = transitions_count(seq_ls, match_state)
    #calculation
    trans_norm_dict, emission_norm_dict = (
        trans_count_normalize(transition_counts, emission_counts))
    #implementation
    hidden_sequence, hmm_residue_sequence = (
        hmm_sequence_generator(trans_norm_dict, emission_norm_dict))
    #print(hidden_sequence)
    print(hmm_residue_sequence)

    ###Questions of the assignment
    #Q1
    if infile == 'test.fasta':
        with open('reduced_alignment.txt', 'w') as f:
            for seq in redu_seq_ls:
                f.write(f'{seq}\n')

    #Q3
    print(trans_norm_dict)
    print(emission_norm_dict)



if __name__ == "__main__":
    main()



'''
##################

My previous transitions_count function:
Reason of being discarded
1. it cannot ignore the '': unmatch and '-', then its output is wrong for doing 
HMM,, because '' cannot be considered as a state, but in the output, it is, 
consequently it messed up the probability, thus cannot proceed from it.

2. It has huge overlapping part, which means, the function is redundant, and 
hard to debug (fix one place, fix all the others).

But, as part of thinking process and my effort, it is worth to be kept as note.
The storage format list of list of tuple are workable and kept in new function.

###################

def transitions_count(seq_ls, match_state):
    """
    input, the sequence and the match state, reduce sequence

    output, the state count
    emission
    """
    transition_counts = []
    emission_counts = []
    for seq in seq_ls:
        match_count = 0
        for i, state in enumerate(match_state):
            #three section is similar
            if i == 0: #section 1, the beginning and first state
                if seq[i] == '-' and state == False: #no emission in this state
                    trans_state = ('Begin', f'')

                    found = False #this is the flag
                    for item in transition_counts:
                        if item[0] == trans_state:
                            item[1] += 1
                            found = True
                            break

                    if found == False:
                        transition_counts.append([trans_state, 1])


                elif seq[i] != '-' and state == False: #Insertion
                    trans_state = ('Begin', f'I{match_count}')
                    #emission adding
                    residue = seq[i]
                    current_state = trans_state[1]
                    emission_found = False
                    for emission_item in emission_counts:
                        if emission_item[0] == (current_state, residue):
                            emission_item[1] += 1
                            emission_found = True
                            break
                    if emission_found == False:
                        emission_counts.append([(current_state, residue), 1])

                    #transition adding
                    found = False
                    for item in transition_counts:
                        if item[0] == trans_state:
                            item[1] += 1
                            found = True
                            break

                    if found == False:
                        transition_counts.append([trans_state, 1])

                elif seq[i] == '-' and state == True: #Deletion #no emission
                    match_count += 1
                    trans_state = ('Begin', f'D{match_count}')

                    found = False
                    for item in transition_counts:
                        if item[0] == trans_state:
                            item[1] += 1
                            found = True
                            break

                    if found == False:
                        transition_counts.append([trans_state, 1])

                elif seq[i] != '-' and state == True:
                    match_count += 1
                    trans_state = ('Begin', f'M{match_count}')
                    # emission adding
                    residue = seq[i]
                    current_state = trans_state[1]
                    emission_found = False
                    for emission_item in emission_counts:
                        if emission_item[0] == (current_state, residue):
                            emission_item[1] += 1
                            emission_found = True
                            break
                    if emission_found == False:
                        emission_counts.append([(current_state, residue), 1])

                    # transition adding
                    found = False
                    for item in transition_counts:
                        if item[0] == trans_state:
                            item[1] += 1
                            found = True
                            break

                    if found == False:
                        transition_counts.append([trans_state, 1])

            elif i < len(match_state) - 1:  # section 2, the state in between
                if seq[i] == '-' and state == False: #no emission
                    pre_state = transition_counts[i - 1][0][1]
                    trans_state = (f'{pre_state}', f'')

                    found = False
                    for item in transition_counts:
                        if item[0] == trans_state:
                            item[1] += 1
                            found = True
                            break

                    if found == False:
                        transition_counts.append([trans_state, 1])

                elif seq[i] != '-' and state == False:
                    pre_state = transition_counts[i - 1][0][1]
                    trans_state = (f'{pre_state}', f'I{match_count}')
                    # emission adding
                    residue = seq[i]
                    current_state = trans_state[1]
                    emission_found = False
                    for emission_item in emission_counts:
                        if emission_item[0] == (current_state, residue):
                            emission_item[1] += 1
                            emission_found = True
                            break
                    if emission_found == False:
                        emission_counts.append([(current_state, residue), 1])

                    # transition adding
                    found = False
                    for item in transition_counts:
                        if item[0] == trans_state:
                            item[1] += 1
                            found = True
                            break

                    if found == False:
                        transition_counts.append([trans_state, 1])

                elif seq[i] == '-' and state == True: #no emission
                    match_count += 1
                    pre_state = transition_counts[i - 1][0][1]
                    trans_state = (f'{pre_state}', f'D{match_count}')

                    found = False
                    for item in transition_counts:
                        if item[0] == trans_state:
                            item[1] += 1
                            found = True
                            break

                    if found == False:
                        transition_counts.append([trans_state, 1])

                elif seq[i] != '-' and state == True:
                    match_count += 1
                    pre_state = transition_counts[i - 1][0][1]
                    trans_state = (f'{pre_state}', f'M{match_count}')
                    # emission adding
                    residue = seq[i]
                    current_state = trans_state[1]
                    emission_found = False
                    for emission_item in emission_counts:
                        if emission_item[0] == (current_state, residue):
                            emission_item[1] += 1
                            emission_found = True
                            break
                    if emission_found == False:
                        emission_counts.append([(current_state, residue), 1])

                    # transition adding
                    found = False
                    for item in transition_counts:
                        if item[0] == trans_state:
                            item[1] += 1
                            found = True
                            break

                    if found == False:
                        transition_counts.append([trans_state, 1])

            else: #section 3, the last state and end state
                if seq[i] == '-' and state == False: # no emission
                    pre_state = transition_counts[i - 1][0][1]
                    trans_state = (f'{pre_state}', f'')
                    end_state = (f'{trans_state[1]}', f'End')
                    found = False
                    for item in transition_counts:
                        if item[0] == trans_state:
                            item[1] += 1
                            found = True
                            break

                    if found == False:
                        transition_counts.append([trans_state, 1])

                    for item in transition_counts:
                        if item[0] == end_state:
                            item[1] += 1
                            found = True
                            break

                    if found == False:
                        transition_counts.append([end_state, 1])

                elif seq[i] != '-' and state == False:
                    pre_state = transition_counts[i - 1][0][1]
                    trans_state = (f'{pre_state}', f'I{match_count}')
                    end_state = (f'{trans_state[1]}', f'End')
                    # emission adding
                    residue = seq[i]
                    current_state = trans_state[1]
                    emission_found = False
                    for emission_item in emission_counts:
                        if emission_item[0] == (current_state, residue):
                            emission_item[1] += 1
                            emission_found = True
                            break
                    if emission_found == False:
                        emission_counts.append([(current_state, residue), 1])

                    # transition adding
                    found = False
                    for item in transition_counts:
                        if item[0] == trans_state:
                            item[1] += 1
                            found = True
                            break

                    if found == False:
                        transition_counts.append([trans_state, 1])

                    for item in transition_counts:
                        if item[0] == end_state:
                            item[1] += 1
                            found = True
                            break

                    if found == False:
                        transition_counts.append([end_state, 1])

                elif seq[i] == '-' and state == True: #no emission
                    match_count += 1
                    pre_state = transition_counts[i - 1][0][1]
                    trans_state = (f'{pre_state}', f'D{match_count}')
                    end_state = (f'{trans_state[1]}', f'End')
                    found = False
                    for item in transition_counts:
                        if item[0] == trans_state:
                            item[1] += 1
                            found = True
                            break

                    if found == False:
                        transition_counts.append([trans_state, 1])

                    for item in transition_counts:
                        if item[0] == end_state:
                            item[1] += 1
                            found = True
                            break

                    if found == False:
                        transition_counts.append([end_state, 1])

                elif seq[i] != '-' and state == True:
                    match_count += 1
                    pre_state = transition_counts[i - 1][0][1]
                    trans_state = (f'{pre_state}', f'M{match_count}')
                    end_state = (f'{trans_state[1]}', f'End')
                    # emission adding
                    residue = seq[i]
                    current_state = trans_state[1]
                    emission_found = False
                    for emission_item in emission_counts:
                        if emission_item[0] == (current_state, residue):
                            emission_item[1] += 1
                            emission_found = True
                            break
                    if emission_found == False:
                        emission_counts.append([(current_state, residue), 1])

                    # transition adding
                    found = False
                    for item in transition_counts:
                        if item[0] == trans_state:
                            item[1] += 1
                            found = True
                            break

                    if found == False:
                        transition_counts.append([trans_state, 1])

                    for item in transition_counts:
                        if item[0] == end_state:
                            item[1] += 1
                            found = True
                            break

                    if found == False:
                        transition_counts.append([end_state, 1])

    return transition_counts, emission_counts
'''